#!/usr/bin/env python3
"""
make_receptor_zones.py -- sample the AIR concentration in a box above each ROI receptor
(volume-average), instead of the area-average on the ROI surface.

Reads receptors.json (centroid_recentred) and writes into --out (a case system/ dir):
  topoSetDict            cellSet(boxToCell) + cellZoneSet per receptor -> roiNZone
  receptorsVolume        volFieldValue(volAverage) per zone; field token '__FIELD__'
                         (the collector substitutes T_CO / T_NOx per pollutant)
  receptor_zone_map.json fo-name -> receptor id + site (for the collector)

A box column [zc-below, zc+height] of half-width HW around each receptor centroid captures
the near-ground breathing air. ROI cells are ~5 m, so keep the column a few cells tall.

Usage:
  python3 make_receptor_zones.py --disp ../dispersionCaseBig --out ../dispersionCaseBig/system \
      --halfwidth 30 --height 12 --below 2
"""
import argparse, json, os

HDR = ("FoamFile\n{\n    version     2.0;\n    format      ascii;\n"
       "    class       dictionary;\n    object      %s;\n}\n"
       "// generated by make_receptor_zones.py -- volume-average receptor sampling\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--disp", required=True, help="dispersion case (uses constant/triSurface/receptors.json)")
    ap.add_argument("--out", required=True, help="target system/ dir")
    ap.add_argument("--halfwidth", type=float, default=30.0, help="box half-width in x,y [m]")
    ap.add_argument("--height", type=float, default=12.0, help="box top above centroid [m]")
    ap.add_argument("--below", type=float, default=2.0, help="box bottom below centroid [m]")
    ap.add_argument("--field", default="__FIELD__",
                    help="field the FO samples. SNAPSHOT post-process: leave as __FIELD__ (collector subs T_CO/T_NOx). "
                         "DURING the solve: pass --field T --no-readfields.")
    ap.add_argument("--no-readfields", action="store_true",
                    help="omit the readFields FO (use when the field is live during the solve, e.g. --field T)")
    ap.add_argument("--wire-controldict", default=None,
                    help="also add #include \"receptorsVolume\" into this controlDict functions{} (idempotent)")
    ap.add_argument("--exclude-zone", default=None,
                    help="cellZone to SUBTRACT from each box (e.g. vegetationZone -- the canopy pins T=0)")
    a = ap.parse_args()

    meta = sorted(json.load(open(os.path.join(a.disp, "constant", "triSurface", "receptors.json"))),
                  key=lambda m: m["id"])
    os.makedirs(a.out, exist_ok=True)
    hw = a.halfwidth

    acts, blocks, mp = [], [], []
    for i, m in enumerate(meta, 1):
        x, y, z = m["centroid_recentred"][:3]
        b0 = (x - hw, y - hw, z - a.below)
        b1 = (x + hw, y + hw, z + a.height)
        blk = ("    {\n"
               "        name    roi%d;\n        type    cellSet;\n        action  new;\n"
               "        source  boxToCell;\n        box     (%.3f %.3f %.3f) (%.3f %.3f %.3f);\n    }\n"
               % (i, b0[0], b0[1], b0[2], b1[0], b1[1], b1[2]))
        if a.exclude_zone:
            blk += ("    {\n"
                    "        name    roi%d;\n        type    cellSet;\n        action  delete;\n"
                    "        source  zoneToCell;\n        zones   (%s);\n    }\n"
                    % (i, a.exclude_zone))
        blk += ("    {\n"
                "        name    roi%dZone;\n        type    cellZoneSet;\n        action  new;\n"
                "        source  setToCellZone;\n        set     roi%d;\n    }" % (i, i))
        acts.append(blk)
        blocks.append(
            "roi%d_vol\n{\n    type            volFieldValue;\n    libs            (fieldFunctionObjects);\n"
            "    fields          (%s);\n    operation       volAverage;\n"
            "    regionType      cellZone;\n    name            roi%dZone;\n"
            "    writeControl    timeStep;\n    writeInterval   100;\n    writeFields     false;\n    log             true;\n}"
            % (i, a.field, i))
        mp.append({"fo": "roi%d_vol" % i, "id": m["id"], "site": m.get("site_name", "")})

    open(os.path.join(a.out, "topoSetDict"), "w").write(
        HDR % "topoSetDict" + "\nactions\n(\n" + "\n".join(acts) + "\n);\n")
    # NOTE: no FoamFile header -- this file is #include-d inside controlDict functions{}
    open(os.path.join(a.out, "receptorsVolume"), "w").write(
        ("// receptor volume-average FOs (volFieldValue volAverage over roiNZone)\n"
         "// generated by make_receptor_zones.py -- #include inside controlDict functions{}\n\n"
         + ("" if a.no_readfields else
            "readReceptorField\n{\n    type    readFields;\n    libs    (fieldFunctionObjects);\n"
            "    fields  (%s);\n}\n\n" % a.field)
         + "\n\n".join(blocks) + "\n"))
    json.dump(mp, open(os.path.join(a.out, "receptor_zone_map.json"), "w"), indent=2)
    if a.wire_controldict and os.path.isfile(a.wire_controldict):
        cd = open(a.wire_controldict).read()
        if "receptorsVolume" in cd:
            print("controlDict already includes receptorsVolume:", a.wire_controldict)
        else:
            if '#include "receptors"' in cd:
                cd = cd.replace('#include "receptors"', '#include "receptors"\n    #include "receptorsVolume"', 1)
            else:
                import re as _re
                cd = _re.sub(r"(functions\s*\n?\s*\{)", r'\1\n    #include "receptorsVolume"', cd, count=1)
            open(a.wire_controldict, "w").write(cd)
            print("wired #include \"receptorsVolume\" into", a.wire_controldict)
    print("wrote topoSetDict, receptorsVolume, receptor_zone_map.json ->", a.out)
    for i, m in enumerate(meta, 1):
        x, y, z = m["centroid_recentred"][:3]
        print("  roi%dZone <- %-10s box x[%.0f,%.0f] y[%.0f,%.0f] z[%.1f,%.1f]"
              % (i, m["id"], x - hw, x + hw, y - hw, y + hw, z - a.below, z + a.height))


if __name__ == "__main__":
    main()
